// Initial catalog — mirrors the original mock data from the React frontend
export const productSeeds = [
  {
    id: 1,
    name: "Luxury Croc Embossed Tote",
    price: 299.0,
    originalPrice: 499.0,
    rating: 4.8,
    reviews: 124,
    colors: [
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/20/600/750" },
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/21/600/750" },
      { name: "Burgundy", code: "#900020", image: "https://picsum.photos/id/22/600/750" },
    ],
    sizes: ["S", "M", "L"],
    style: "Tote",
    material: "Genuine Leather",
    stock: 15,
    isBestSeller: true,
    isNew: false,
    mainImage: "https://picsum.photos/id/20/600/750",
    gallery: [
      "https://picsum.photos/id/20/600/750",
      "https://picsum.photos/id/21/600/750",
      "https://picsum.photos/id/22/600/750",
      "https://picsum.photos/id/23/600/750",
    ],
    description:
      "Elegant croc-embossed leather tote handcrafted from premium Italian leather. A statement carry-all designed for everyday luxury, finished with rose-gold hardware and a soft suede interior.",
    gender: "Women",
  },
  {
    id: 2,
    name: "Velvet Rose Evening Clutch",
    price: 189.0,
    originalPrice: 249.0,
    rating: 4.9,
    reviews: 87,
    colors: [
      { name: "Blush Pink", code: "#F5C2C7", image: "https://picsum.photos/id/64/600/750" },
      { name: "Burgundy", code: "#900020", image: "https://picsum.photos/id/65/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/66/600/750" },
    ],
    sizes: ["One Size"],
    style: "Clutch",
    material: "Velvet",
    stock: 8,
    isBestSeller: false,
    isNew: true,
    mainImage: "https://picsum.photos/id/64/600/750",
    gallery: [
      "https://picsum.photos/id/64/600/750",
      "https://picsum.photos/id/65/600/750",
      "https://picsum.photos/id/66/600/750",
    ],
    description:
      "A delicate velvet evening clutch dressed with a hand-stitched rose accent. Perfect for cocktail nights, weddings, and red-carpet moments.",
    gender: "Women",
  },
  {
    id: 3,
    name: "Parisian Quilted Crossbody",
    price: 329.0,
    originalPrice: null,
    rating: 4.7,
    reviews: 203,
    colors: [
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/30/600/750" },
      { name: "Navy", code: "#1A2A3A", image: "https://picsum.photos/id/31/600/750" },
      { name: "Cream", code: "#F5F0E6", image: "https://picsum.photos/id/32/600/750" },
    ],
    sizes: ["S", "M"],
    style: "Crossbody",
    material: "Lambskin",
    stock: 25,
    isBestSeller: true,
    isNew: false,
    mainImage: "https://picsum.photos/id/30/600/750",
    gallery: [
      "https://picsum.photos/id/30/600/750",
      "https://picsum.photos/id/31/600/750",
      "https://picsum.photos/id/32/600/750",
      "https://picsum.photos/id/33/600/750",
    ],
    description:
      "Iconic Parisian quilting on whisper-soft lambskin, with an adjustable chain strap and gold-tone clasp. Light enough for day, refined enough for night.",
    gender: "Women",
  },
  {
    id: 4,
    name: "Ivory Pearl Mini Bag",
    price: 219.0,
    originalPrice: 279.0,
    rating: 4.6,
    reviews: 56,
    colors: [
      { name: "Cream", code: "#F5F0E6", image: "https://picsum.photos/id/96/600/750" },
      { name: "Blush Pink", code: "#F5C2C7", image: "https://picsum.photos/id/97/600/750" },
    ],
    sizes: ["XS", "S"],
    style: "Mini",
    material: "Satin",
    stock: 4,
    isBestSeller: false,
    isNew: true,
    mainImage: "https://picsum.photos/id/96/600/750",
    gallery: ["https://picsum.photos/id/96/600/750", "https://picsum.photos/id/97/600/750"],
    description:
      "A petite satin mini bag dotted with hand-set pearls. Romantic, refined and ready for the most photographed moments of your week.",
    gender: "Women",
  },
  {
    id: 5,
    name: "Heritage Bridle Satchel",
    price: 459.0,
    originalPrice: 599.0,
    rating: 4.9,
    reviews: 312,
    colors: [
      { name: "Brown", code: "#5B3A1F", image: "https://picsum.photos/id/40/600/750" },
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/41/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/42/600/750" },
    ],
    sizes: ["M", "L"],
    style: "Satchel",
    material: "Genuine Leather",
    stock: 19,
    isBestSeller: true,
    isNew: false,
    mainImage: "https://picsum.photos/id/40/600/750",
    gallery: [
      "https://picsum.photos/id/40/600/750",
      "https://picsum.photos/id/41/600/750",
      "https://picsum.photos/id/42/600/750",
    ],
    description:
      "An heirloom-grade satchel in vegetable-tanned bridle leather. Solid brass hardware, hand-stitched seams, and a structured silhouette built to age beautifully.",
    gender: "Women",
  },
  {
    id: 6,
    name: "Gilded Chain Shoulder Bag",
    price: 379.0,
    originalPrice: null,
    rating: 4.7,
    reviews: 142,
    colors: [
      { name: "Gold", code: "#D4AF37", image: "https://picsum.photos/id/50/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/51/600/750" },
      { name: "Burgundy", code: "#900020", image: "https://picsum.photos/id/52/600/750" },
    ],
    sizes: ["S", "M"],
    style: "Shoulder",
    material: "Lambskin",
    stock: 11,
    isBestSeller: false,
    isNew: false,
    mainImage: "https://picsum.photos/id/50/600/750",
    gallery: [
      "https://picsum.photos/id/50/600/750",
      "https://picsum.photos/id/51/600/750",
      "https://picsum.photos/id/52/600/750",
    ],
    description:
      "A polished shoulder bag with a sculpted gold chain and softly pleated lambskin body. Tailored for the woman who knows the power of a quiet entrance.",
    gender: "Women",
  },
  {
    id: 7,
    name: "Riviera Straw Bucket",
    price: 169.0,
    originalPrice: 219.0,
    rating: 4.5,
    reviews: 78,
    colors: [
      { name: "Natural", code: "#E8D8B8", image: "https://picsum.photos/id/76/600/750" },
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/77/600/750" },
    ],
    sizes: ["M"],
    style: "Bucket",
    material: "Woven",
    stock: 22,
    isBestSeller: false,
    isNew: true,
    mainImage: "https://picsum.photos/id/76/600/750",
    gallery: ["https://picsum.photos/id/76/600/750", "https://picsum.photos/id/77/600/750"],
    description:
      "Hand-woven straw bucket bag with leather drawstring closure. Sun-soaked, summer-ready, and effortlessly chic from market to marina.",
    gender: "Women",
  },
  {
    id: 8,
    name: "Onyx Structured Top-Handle",
    price: 549.0,
    originalPrice: 699.0,
    rating: 4.9,
    reviews: 187,
    colors: [
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/60/600/750" },
      { name: "Navy", code: "#1A2A3A", image: "https://picsum.photos/id/61/600/750" },
      { name: "Burgundy", code: "#900020", image: "https://picsum.photos/id/62/600/750" },
    ],
    sizes: ["S", "M", "L"],
    style: "Top-Handle",
    material: "Genuine Leather",
    stock: 7,
    isBestSeller: true,
    isNew: false,
    mainImage: "https://picsum.photos/id/60/600/750",
    gallery: [
      "https://picsum.photos/id/60/600/750",
      "https://picsum.photos/id/61/600/750",
      "https://picsum.photos/id/62/600/750",
    ],
    description:
      "A boardroom-to-ballroom top-handle bag in glossy calfskin. Architectural lines, palladium feet, and a removable shoulder strap for versatility.",
    gender: "Women",
  },
  {
    id: 9,
    name: "Suede Fringe Hobo",
    price: 259.0,
    originalPrice: null,
    rating: 4.4,
    reviews: 64,
    colors: [
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/70/600/750" },
      { name: "Brown", code: "#5B3A1F", image: "https://picsum.photos/id/71/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/72/600/750" },
    ],
    sizes: ["M", "L"],
    style: "Hobo",
    material: "Suede",
    stock: 13,
    isBestSeller: false,
    isNew: false,
    mainImage: "https://picsum.photos/id/70/600/750",
    gallery: [
      "https://picsum.photos/id/70/600/750",
      "https://picsum.photos/id/71/600/750",
      "https://picsum.photos/id/72/600/750",
    ],
    description:
      "A slouchy suede hobo finished with whisper-soft fringe. Free-spirited, generously sized, and weekend-bound.",
    gender: "Women",
  },
  {
    id: 10,
    name: "Champagne Beaded Wristlet",
    price: 149.0,
    originalPrice: 199.0,
    rating: 4.6,
    reviews: 41,
    colors: [
      { name: "Gold", code: "#D4AF37", image: "https://picsum.photos/id/80/600/750" },
      { name: "Cream", code: "#F5F0E6", image: "https://picsum.photos/id/81/600/750" },
      { name: "Blush Pink", code: "#F5C2C7", image: "https://picsum.photos/id/82/600/750" },
    ],
    sizes: ["One Size"],
    style: "Clutch",
    material: "Beaded",
    stock: 0,
    isBestSeller: false,
    isNew: false,
    mainImage: "https://picsum.photos/id/80/600/750",
    gallery: [
      "https://picsum.photos/id/80/600/750",
      "https://picsum.photos/id/81/600/750",
      "https://picsum.photos/id/82/600/750",
    ],
    description:
      "Hand-beaded wristlet that catches the light from across the room. A celebratory finishing touch for evening looks.",
    gender: "Women",
  },
  {
    id: 11,
    name: "Modernist Leather Backpack",
    price: 399.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 156,
    colors: [
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/90/600/750" },
      { name: "Brown", code: "#5B3A1F", image: "https://picsum.photos/id/91/600/750" },
      { name: "Navy", code: "#1A2A3A", image: "https://picsum.photos/id/92/600/750" },
    ],
    sizes: ["M", "L"],
    style: "Backpack",
    material: "Genuine Leather",
    stock: 17,
    isBestSeller: false,
    isNew: true,
    mainImage: "https://picsum.photos/id/90/600/750",
    gallery: [
      "https://picsum.photos/id/90/600/750",
      "https://picsum.photos/id/91/600/750",
      "https://picsum.photos/id/92/600/750",
    ],
    description:
      "A streamlined leather backpack with a padded laptop sleeve and convertible shoulder strap. Minimal lines, maximum function.",
    gender: "Women",
  },
  {
    id: 12,
    name: "Atelier Mini Bucket",
    price: 239.0,
    originalPrice: 319.0,
    rating: 4.7,
    reviews: 98,
    colors: [
      { name: "Burgundy", code: "#900020", image: "https://picsum.photos/id/100/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/101/600/750" },
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/102/600/750" },
    ],
    sizes: ["XS", "S"],
    style: "Bucket",
    material: "Lambskin",
    stock: 6,
    isBestSeller: false,
    isNew: false,
    mainImage: "https://picsum.photos/id/100/600/750",
    gallery: [
      "https://picsum.photos/id/100/600/750",
      "https://picsum.photos/id/101/600/750",
      "https://picsum.photos/id/102/600/750",
    ],
    description:
      "A petite bucket bag in lambskin so soft it feels like silk. Drawstring closure, suede lining, and a name plaque finished in rose gold.",
    gender: "Women",
  },
  {
    id: 13,
    name: "Equestrian Saddle Bag",
    price: 419.0,
    originalPrice: null,
    rating: 4.8,
    reviews: 211,
    colors: [
      { name: "Brown", code: "#5B3A1F", image: "https://picsum.photos/id/110/600/750" },
      { name: "Tan", code: "#D2B48C", image: "https://picsum.photos/id/111/600/750" },
      { name: "Black", code: "#1A1A1A", image: "https://picsum.photos/id/112/600/750" },
    ],
    sizes: ["S", "M"],
    style: "Crossbody",
    material: "Genuine Leather",
    stock: 9,
    isBestSeller: true,
    isNew: false,
    mainImage: "https://picsum.photos/id/110/600/750",
    gallery: [
      "https://picsum.photos/id/110/600/750",
      "https://picsum.photos/id/111/600/750",
      "https://picsum.photos/id/112/600/750",
    ],
    description:
      "An equestrian-inspired saddle bag with a polished horsebit clasp and adjustable strap. Heritage craftsmanship in a modern silhouette.",
    gender: "Women",
  },
];
